version: '3.8'

services:
  frontend:
    image: dockerizzz/my-frontend:latest # REPLACE with your actual frontend image name
    container_name: frontend_container
    ports:
      - "3000:3000" # Host port: Container port
    restart: always

  backend:
    image: dockerizzz/my-backend:latest # REPLACE with your actual backend image name
    container_name: backend_container
    ports:
      - "5000:5000" # Host port: Container port
    restart: always
    environment:
      # Example: pass the frontend URL if needed
      - FRONTEND_URL=http://<EC2_PUBLIC_IP>:3000